modLoader = "javafml"
loaderVersion = "[37,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "eternal_starlight"
version = "${version}"
displayName = "Eternal Starlight"
authors = "LeoLezury"
description = '''
A Minecraft dimension mod with structures for you to explore and bosses for you to defeat!
'''
#logoFile = "logo.png"

[[dependencies.eternal_starlight]]
modId = "forge"
mandatory = true
versionRange = "[41.0.22,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.eternal_starlight]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"