modLoader = "javafml"
loaderVersion = "*"
#issueTrackerURL = ""
license = "MIT"

[[mixins]]
config = "eternal_starlight.mixins.json"
[[mixins]]
config = "eternal_starlight-common.mixins.json"

[[mods]]
modId = "eternal_starlight"
version = "${version}"
displayName = "Eternal Starlight"
authors = "LeoLezury"
description = '''
A Minecraft dimension mod with structures for you to explore and bosses for you to defeat!
'''
#logoFile = "logo.png"

[[dependencies.eternal_starlight]]
modId = "neoforge"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.eternal_starlight]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,1.22)"
ordering = "NONE"
side = "BOTH"